slam_toolbox:
  ros__parameters:
    # 1. Frame Setup
    odom_frame: odom
    base_frame: base_link_icp
    map_frame: map
    scan_topic: /scan

    # 2. การทำงาน
    mode: mapping # สำหรับสร้างแผนที่ใหม่
    use_sim_time: true

    # 3. Pose Graph & Optimization
    do_loop_closing: false
    max_lasso_dist: 2.0
    minimum_time_interval: 0.5
    
    # 4. Scan Matching
    max_condition_number: 10000.0
    max_res_dist: 0.05
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5